apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: windstorm-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    windstorm:
      port: "12000"
      endpoint: /windstorm
      method: POST
