apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: windstorm-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: windstorm-webhook
    eventName: windstorm
  triggers:
  - template:
      name: windstorm
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: windstorm-
              labels:
                app: windstorm
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args:
                - "This is the referring webhook you sent me:\n"
                - ""
                - "\nThis is the payload:\n"
                - ""
              - name: publish
                image: docker.io/westfallio/windstorm-mage:v0.0.1
                env:
                - name: WINDRUNNERHOST
                  value: http://windrunner-webhook-eventsource-svc.argo-events:12000/windrunner
                - name: WINDSTORMAPIHOST
                  value: http://windstorm-api-service.windstorm:8000/
                - name: SQLHOST
                  value: postgres-postgresql.windstorm:5432
                - name: DBUSER  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: username     # 'key' subcomponent of the secret
                - name: DBPASS  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: password     # 'key' subcomponent of the secret
                - name: DBTABLE  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: table     # 'key' subcomponent of the secret
                command: ["python"]
                args:
                - "src/main.py"
                - ""
                - ""
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.source
            dest: spec.containers.0.args.1
          - src:
              dependencyName: payload
              dataKey: body.payload
            dest: spec.containers.0.args.3
          - src:
              dependencyName: payload
              dataKey: body.source
            dest: spec.containers.1.args.1
          - src:
              dependencyName: payload
              dataKey: body.payload
            dest: spec.containers.1.args.2
